version: '3.8'

services:
  project_db:
    container_name: project_db
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: project_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
#    volumes:
#        - ./data:/var/lib/postgresql/data